# Martin Guo
# martin.guo@irdeto.com
# 2016-06-13

Phony: build

build: 
	docker build -t base.hadoop.cluster  .
    
build_without_cache: 
	docker build -no-cache -t base.hadoop.cluster  .
    
run:
	docker run -d \
	-t base.hadoop.cluster





